{
 "title": "Node Rewards Queue Prometheus",
 "description": "Graphs for Bull Queues \n\nhttps://github.com/UpHabit/bull_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(bull_queue_waiting) by (prefix, queue)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(bull_queue_waiting  / rate(bull_queue_completed[5m])) by (queue, prefix)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Queue States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bull_queue_completed[5m])) * 60",
     "legendFormat": "Complete Rate"
    },
    {
     "expr": "sum(rate(bull_queue_failed[5m])) * 60",
     "legendFormat": "Fail Rate"
    },
    { "expr": "sum(bull_queue_active)", "legendFormat": "Active" },
    { "expr": "sum(bull_queue_waiting)", "legendFormat": "Waiting" },
    { "expr": "sum(bull_queue_delayed)", "legendFormat": "Delayed" },
    { "expr": "sum(bull_queue_failed)", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Failures By Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(bull_queue_failed) by (queue)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Job Duration 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bull_queue_complete_duration { quantile = \"0.9\" }) by (queue)",
     "legendFormat": "{{ queue }}"
    }
   ]
  }
 ]
}